///////////////////////////////////////////////////////////
//  ConductingEquipment.cs
//  Implementation of the Class ConductingEquipment
//  Generated by Enterprise Architect
//  Created on:      24-Aug-2016 11:29:39 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
    /// <summary>
    /// The parts of the AC power system that are designed to carry current or that are
    /// conductively connected through terminals.
    /// </summary>
    [Serializable()]
    public class ConductingEquipment : Equipment {

		public ConductingEquipment(){

		}

		~ConductingEquipment(){

		}

	}//end ConductingEquipment

}//end namespace Core