///////////////////////////////////////////////////////////
//  Equipment.cs
//  Implementation of the Class Equipment
//  Generated by Enterprise Architect
//  Created on:      24-Aug-2016 11:29:39 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
    /// <summary>
    /// The parts of a power system that are physical devices, electronic or mechanical.
    /// 
    /// </summary>
    [Serializable()]
    public class Equipment : PowerSystemResource {

		public Equipment(){

		}

		~Equipment(){

		}

	}//end Equipment

}//end namespace Core