///////////////////////////////////////////////////////////
//  VoltageLevel.cs
//  Implementation of the Class VoltageLevel
//  Generated by Enterprise Architect
//  Created on:      24-Aug-2016 11:29:40 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
    /// <summary>
    /// A collection of equipment at one common system voltage forming a switchgear.
    /// The equipment typically consist of breakers, busbars, instrumentation, control,
    /// regulation and protection devices as well as assemblies of all these.
    /// </summary>
    [Serializable()]
    public class VoltageLevel : EquipmentContainer {

		/// <summary>
		/// The bays within this voltage level.
		/// </summary>
		public List<Bay> Bays;
		/// <summary>
		/// The base voltage used for all equipment within the voltage level.
		/// </summary>
		public CIM.IEC61970.Base.Core.BaseVoltage BaseVoltage { get; set; }

        public VoltageLevel(){

		}

		~VoltageLevel(){

		}
        public override string ToString()
        {
            return BaseVoltage.nominalVoltage.ToString();
        }

    }//end VoltageLevel

}//end namespace Core