///////////////////////////////////////////////////////////
//  SynchronousMachineKind.cs
//  Implementation of the Enumeration SynchronousMachineKind
//  Generated by Enterprise Architect
//  Created on:      24-Aug-2016 11:29:40 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Synchronous machine type.
	/// </summary>
	public enum SynchronousMachineKind : int {

		generator,
		condenser,
		generatorOrCondenser,
		motor,
		generatorOrMotor,
		motorOrCondenser,
		generatorOrCondenserOrMotor

	}//end SynchronousMachineKind

}//end namespace Wires